slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # Frames
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint

    # Topics
    scan_topic: /scan

    # Publish TF map->odom
    publish_tf: true
    transform_publish_period: 0.05

    # SLAM mode
    mode: mapping

    # General
    debug_logging: false
    throttle_scans: 1
    minimum_time_interval: 0.2
    transform_timeout: 0.2

    # Map update / publish rates
    map_update_interval: 1.0
    resolution: 0.05
    max_laser_range: 8.0
    minimum_travel_distance: 0.10
    minimum_travel_heading: 0.10

    # Loop closure
    do_loop_closing: true
    loop_search_maximum_distance: 3.0

    # Scan matching
    use_scan_matching: true
    use_scan_barycenter: true

    # Correlation (scan matcher)
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Fine search
    fine_search_angle_offset: 0.00349
    fine_search_angle_resolution: 0.001745
    fine_search_range_offset: 0.05
    fine_search_range_resolution: 0.01

    # Kinematics
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0

    # If you ever see TF timing issues, you can try:
    # tf_buffer_duration: 30.0
