slam_toolbox:
  ros__parameters:
    use_sim_time: true
    slam_mode: "mapping"          # online mapping
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "scan"
    resolution: 0.05
    max_laser_range: 8.0
    minimum_time_interval: 0.1
    transform_timeout: 1.0
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: false
